version: "3"
services:
  server:
    container_name: ktp-server
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    networks:
      - backend
    ports:
    - "8082:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
  db:
    image: mariadb:10.3
    container_name: ktp-database
    env_file:
      - .env
    ports:
      - "3308:3306" 
    restart: unless-stopped
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql

volumes:
  data:
networks:
  backend:
    driver: bridge