version: '3'
services:
  ktp-app:
    build: .
    working_dir: /src
    ports:
      - 8080:8080
    volumes: 
      - ./config:/src/config
    links:
      - 'mariadb-ktp-dbs'
    networks:  
      - testing
  mariadb-ktp-dbs:
    image: mariadb:10.3
    networks: 
      - testing
networks: 
  testing:
    driver: bridge