version: "3"
services:
  db:
    image: mariadb:10.3
    container_name: ktp-database
    # env_file:
    #   - .env
    ports:
      - "5000:3306"
    networks:
      - backend
    volumes:
      - data:/var/lib/mysql/data
  server:
    container_name: ktp-server
    build:
      context: .
      dockerfile: Dockerfile
    # env_file: .env
    depends_on:
      - db
    networks:
      - backend
    ports:
    - "8080:8080"
volumes:
  data:
networks:
  backend:
    driver: bridge